
import "@/styles/style.scss";
import Script from "next/script";
import { Rubik } from "next/font/google";

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Bedjoekopi',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>

      {/* <!-- jquery js --> */}
      <Script src="js/plugins/jquery.min.js"></Script>
      {/* <!-- smooth scroll js --> */}
      <Script src="js/plugins/smooth-scroll.js"></Script>
      {/* <!-- swup js --> */}
      <Script src="js/plugins/swup.min.js"></Script>
      {/* <!-- swiper js --> */}
      <Script src="js/plugins/swiper.min.js"></Script>
      {/* <!-- datepicker js --> */}
      <Script src="js/plugins/datepicker.js"></Script>
      {/* <!-- isotope js --> */}
      <Script src="js/plugins/isotope.js"></Script>
      {/* <!-- sticky --> */}
      <Script src="js/plugins/sticky.js"></Script>
      {/* <!-- mapbox js --> */}
      <Script src="js/plugins/mapbox.min.js"></Script>
      {/* <!-- fancybox js --> */}
      <Script src="js/plugins/fancybox.min.js"></Script>
      {/* <!-- bedjoekopi js --> */}
      <Script src="js/main.js"></Script>
    </html>
  );
}

export default RootLayout;